server:
  port: 8081
  shutdown: graceful

spring:
  application:
    name: core-orchestrator
    version: 1.0.0
    description: Core processes orchestrator
    team:
      name: Catalis Development
      email: dev@catalis.com

# H2 Database Configuration
  r2dbc:
    url: r2dbc:h2:mem:///orchestratordb;DB_CLOSE_DELAY=-1
    username: sa
    password:

# Zeebe configuration
camunda.client.zeebe.base-url: http://localhost:26500
# Worker configuration
camunda.client.zeebe.defaults.name: user-info-worker
# Configuración de logging
logging.level.com.example.orchestrator: INFO

# Clients basePath
api-configuration:
  sca:
    base-path: http://localhost:8086
  notifications:
    base-path: http://localhost:8088

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tagsSorter: alpha
    operationsSorter: method
    docExpansion: none
    filter: true
  packages-to-scan: com.catalis.core.orchestrator.web.controllers
  paths-to-match: /api/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: INFO
    com.catalis: DEBUG
    org.springframework.r2dbc: DEBUG
    org.flywaydb: DEBUG

---
spring:
  config:
    activate:
      on-profile: testing

logging:
  level:
    root: INFO
    com.catalis: DEBUG
    org.springframework.r2dbc: INFO

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

---
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: WARN
    com.catalis: INFO
    org.springframework: WARN

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false