name: Publish Pipeline

on:
  push:
    branches: ["main", "develop"]

jobs:
  build-jar:
    uses: firefly-oss/cicd/.github/workflows/build-maven.yaml@main
    with:
      java-version: "21"
      skip-tests: false
      jar-path: "core-orchestrator-web/target/core-orchestrator.jar"
    secrets:
      PAT_GITHUB_PACKAGE: ${{ secrets.PAT_GITHUB_PACKAGE }}